version: 2.1

orbs:
  go-module: timakin/go-module@0.0.5
  aws-ecr: circleci/aws-ecr@3.0.0
  aws-cli: circleci/aws-cli@0.1.9

executors:
  test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/po3rin/github_link_creator

jobs:
  test:
    executor:
      name: test
    steps:
      - checkout
      - setup_remote_docker
      - go-module/setup

      # - run:
      #     name: Setup Code Climate test-reporter
      #     command: |
      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #       chmod +x ./cc-test-reporter

      - run:
          name: Run tests
          command: |
            # ./cc-test-reporter before-build
            go test ./... -coverprofile=c.out
            # ./cc-test-reporter after-build -d -r $CODE_CLIMATE_TOKEN --coverage-input-type gocov -p ./ --exit-code $?
      - run:
          name: Convert html
          command: go tool cover -html c.out -o c.html

      - store_artifacts:
          path: c.out
          destination: c.out

      - store_artifacts:
          path: c.html
          destination: c.html

  deploy_ecr:
    executor: aws-cli/default
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/install
      - aws-cli/configure:
          aws-region: AWS_REGION

      - run:
          name: cp Dockerfile
          command: |
            cp Dockerfile.prod Dockerfile

      - aws-ecr/build-and-push-image:
          dockerfile: ./Dockerfile
          account-url: ECR_ENDPOINT
          repo: $CIRCLE_PROJECT_REPONAME

  deploy_ecs:
    executor: aws-cli/default
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-region: AWS_REGION
      - aws-ecr/ecr-login
      - run:
          name: install ecs-deploy
          command: |
            curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
            sudo chmod +x /usr/bin/ecs-deploy
      - deploy:
          name: deploy ecs
          command: |
            ecs-deploy -c ghlinkcard-container \
              -n ghlinkcard \
              -r ap-northeast-1 --timeout 240 \
              -i $ECR_ENDPOINT/$CIRCLE_PROJECT_REPONAME:latest

workflows:
  version: 2.0
  test_build_deploy:
    jobs:
      - test
      - deploy_ecr:
          requires:
            - test
          filters:
            branches:
              only: release
      - deploy_ecs:
          requires:
            - deploy_ecr
          filters:
            branches:
              only: release
